# Generated by Django 3.1.2 on 2020-10-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_date',
        ),
    ]
